"""Initial migration

Revision ID: 00746ea0b291
Revises: 
Create Date: 2026-02-17 15:10:21.485270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00746ea0b291'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('college', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college', 'department', name='uq_college_department_hod')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=True)

    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=200), nullable=False),
    sa.Column('college', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('semester', sa.String(length=10), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('slot_start_date', sa.Date(), nullable=True),
    sa.Column('slot_end_date', sa.Date(), nullable=True),
    sa.Column('slot_label', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index('idx_batch_college_dept', ['college', 'department'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_batch_id'), ['batch_id'], unique=True)

    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('semester', sa.String(length=10), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('college', sa.String(length=100), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.create_index('idx_faculty_college_dept', ['college', 'department'], unique=False)
        batch_op.create_index('idx_faculty_lookup', ['college', 'department', 'year', 'semester', 'section'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_college'), ['college'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_department'), ['department'], unique=False)

    op.create_table('batch_faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'faculty_id', name='uq_batch_faculty')
    )
    op.create_table('feedback_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_db_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['batch_db_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_submissions', schema=None) as batch_op:
        batch_op.create_index('idx_submission_batch', ['batch_db_id'], unique=False)

    op.create_table('feedback_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 10', name='chk_rating_range'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['feedback_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_ratings', schema=None) as batch_op:
        batch_op.create_index('idx_rating_faculty', ['faculty_id'], unique=False)
        batch_op.create_index('idx_rating_submission', ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_ratings', schema=None) as batch_op:
        batch_op.drop_index('idx_rating_submission')
        batch_op.drop_index('idx_rating_faculty')

    op.drop_table('feedback_ratings')
    with op.batch_alter_table('feedback_submissions', schema=None) as batch_op:
        batch_op.drop_index('idx_submission_batch')

    op.drop_table('feedback_submissions')
    op.drop_table('batch_faculty')
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_department'))
        batch_op.drop_index(batch_op.f('ix_faculty_college'))
        batch_op.drop_index(batch_op.f('ix_faculty_code'))
        batch_op.drop_index('idx_faculty_lookup')
        batch_op.drop_index('idx_faculty_college_dept')

    op.drop_table('faculty')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_batch_id'))
        batch_op.drop_index('idx_batch_college_dept')

    op.drop_table('batches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    # ### end Alembic commands ###
