"""initial

Revision ID: 0b9527a44d5f
Revises: 00746ea0b291
Create Date: 2026-03-07 11:23:29.740553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9527a44d5f'
down_revision = '00746ea0b291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_submissions', schema=None) as batch_op:
        batch_op.create_index('idx_submission_ip_batch', ['batch_db_id', 'ip_address'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('reset_otp_expiry', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_college_department_hod'), type_='unique')
        batch_op.create_index('idx_user_college_dept', ['college', 'department'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_user_college_dept')
        batch_op.create_unique_constraint(batch_op.f('uq_college_department_hod'), ['college', 'department'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('reset_otp_expiry')
        batch_op.drop_column('reset_otp')

    with op.batch_alter_table('feedback_submissions', schema=None) as batch_op:
        batch_op.drop_index('idx_submission_ip_batch')

    # ### end Alembic commands ###
