"""remove code

Revision ID: 2a3128a7a9af
Revises: 0b9527a44d5f
Create Date: 2026-04-14 16:21:18.974005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3128a7a9af'
down_revision = '0b9527a44d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('section_name', sa.String(length=50), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('college', 'department', 'year', 'branch', 'section_name', name='uq_dept_section')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_students', sa.Integer(), nullable=True))

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_code'))
        batch_op.drop_column('code')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_mobile'), ['mobile'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_mobile'))

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_faculty_code'), ['code'], unique=False)

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_column('total_students')

    op.drop_table('department_sections')
    # ### end Alembic commands ###
